# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(100, 80, 871, 271))
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 848, 1222))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 1200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.cmb_fileList = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_fileList.setGeometry(QtCore.QRect(410, 380, 211, 41))
        self.cmb_fileList.setObjectName("cmb_fileList")
        
        self.btn_Download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Download.setGeometry(QtCore.QRect(460, 450, 121, 41))
        self.btn_Download.setObjectName("btn_Download")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.wdgt_file = QtWidgets.QWidget(self.frame)
        self.pgr_file = QtWidgets.QProgressBar(self.wdgt_file)
        self.lbl_filename = QtWidgets.QLabel(self.wdgt_file)
        self.lbl_numSeed = QtWidgets.QLabel(self.wdgt_file)
        self.lbl_numLeachers = QtWidgets.QLabel(self.wdgt_file)
        self.lbl_seedImg = QtWidgets.QLabel(self.wdgt_file)
        self.lbl_LeachImg = QtWidgets.QLabel(self.wdgt_file)
       # self.btn_Download.clicked.connect(Peer.download)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        #self.lbl_filename.setText(_translate("MainWindow", "TextLabel"))
        #self.lbl_numSeed.setText(_translate("MainWindow", "TextLabel"))
        #self.lbl_numLeachers.setText(_translate("MainWindow", "TextLabel"))
        self.btn_Download.setText(_translate("MainWindow", "PushButton"))
    def download(self,file_name):
        file_name = self.cmb_fileList.currentText()
        
    
    def update_file_list(self, file_list):
        bool = False

        if self.cmb_fileList.count() == 0:
            for i in file_list.keys():
                self.cmb_fileList.addItem(i)
        else:

            for i in file_list.keys():
                

                for j in range(self.cmb_fileList.count()):
                    if i == self.cmb_fileList.itemText(j):
                        bool =True
                if bool == False:

                    self.cmb_fileList.addItem(i)
                    bool = False
    def add_file_item(self,file_name):
        
        self.wdgt_file.setGeometry(QtCore.QRect(40, 10, 750, 50))
        self.wdgt_file.setAutoFillBackground(True)
        self.wdgt_file.setObjectName("wdgt_file")
        
        self.pgr_file.setGeometry(QtCore.QRect(300, 15, 121, 23))
        self.pgr_file.setStyleSheet("")
        self.pgr_file.setProperty("value", 24)
        self.pgr_file.setInvertedAppearance(False)
        self.pgr_file.setObjectName("pgr_file")
        
        self.lbl_filename.setGeometry(QtCore.QRect(30, 15, 55, 16))
        self.lbl_filename.setObjectName("lbl_filename")
        self.lbl_filename.setText(file_name)
        
        self.lbl_numSeed.setGeometry(QtCore.QRect(580, 15, 55, 16))
        self.lbl_numSeed.setObjectName("lbl_numSeed")
        
        self.lbl_numLeachers.setGeometry(QtCore.QRect(680, 15, 55, 16))
        self.lbl_numLeachers.setObjectName("lbl_numLeachers")
        
        self.lbl_seedImg.setGeometry(QtCore.QRect(550, 10, 21, 20))
        self.lbl_seedImg.setText("")
        self.lbl_seedImg.setPixmap(QtGui.QPixmap("../../CSC3002F - Assignment 1/LMKtorrent/src/assets/frame0/image_5.png"))
        self.lbl_seedImg.setScaledContents(True)
        self.lbl_seedImg.setObjectName("lbl_seedImg")
        
        self.lbl_LeachImg.setGeometry(QtCore.QRect(650, 15, 21, 20))
        self.lbl_LeachImg.setText("")
        self.lbl_LeachImg.setPixmap(QtGui.QPixmap("../../CSC3002F - Assignment 1/LMKtorrent/src/assets/frame0/image_6.png"))
        self.lbl_LeachImg.setScaledContents(True)
        self.lbl_LeachImg.setObjectName("lbl_LeachImg")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        
                    
            
                


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
